### ISSUE TITLE
Can't run `pack` due to Pydantic Error: `RootModel` does not support setting `model_config['extra']`

### ISSUE THREAD

**Issue by trentfridey** [emscripten-forge/empack#78]
* empack version: 3.1.0
* Operating System: ubuntu 22.04
* Compiler: emscripten

### Description

Packing an environment in a GitHub action fails due to a Pydantic error from https://github.com/emscripten-forge/empack/blob/d6ff060fda66306ffb1367ac0e7f04ccad5f4233/empack/file_patterns.py#L33

The error is:

```
pydantic.errors.PydanticUserError: `RootModel` does not support setting `model_config['extra']`
```

<details>
<summary>Traceback</summary>
<pre>
Traceback (most recent call last):
  File "/opt/conda/bin/empack", line 7, in <module>
    from empack.cli.main import app
  File "/opt/conda/lib/python3.9/site-packages/empack/cli/main.py", line 2, in <module>
    from .pack import *  # noqa: F403
  File "/opt/conda/lib/python3.9/site-packages/empack/cli/pack.py", line 6, in <module>
    from empack.file_patterns import pkg_file_filter_from_yaml
  File "/opt/conda/lib/python3.9/site-packages/empack/file_patterns.py", line 33, in <module>
    class FilePattern(RootModel, extra="forbid"):
  File "/opt/conda/lib/python3.9/site-packages/pydantic/_internal/_model_construction.py", line [12](https://github.com/qutip/qutip-virtual-lab/actions/runs/5914370171/job/16039628729#step:9:13)3, in __new__
    cls: type[BaseModel] = super().__new__(mcs, cls_name, bases, namespace, **kwargs)  # type: ignore
  File "/opt/conda/lib/python3.9/abc.py", line 106, in __new__
    cls = super().__new__(mcls, name, bases, namespace, **kwargs)
  File "/opt/conda/lib/python3.9/site-packages/pydantic/root_model.py", line 50, in __init_subclass__
    raise PydanticUserError(
pydantic.errors.PydanticUserError: `RootModel` does not support setting `model_config['extra']`
</pre>
</details>

### What I Did

You can see the failed CI run log [here](https://github.com/qutip/qutip-virtual-lab/actions/runs/5914370171/job/16039628729) and the workflow config file [here](https://github.com/qutip/qutip-virtual-lab/blob/main/.github/workflows/deploy.yaml), but in summary, I tried running 

```
        empack pack env \
        --env-prefix=/opt/conda/envs/web \
        --relocate-prefix=/ \
        --no-use-cache \
        --outdir=./public/empack \
        --config=empack_config.yaml
```

Oddly enough, this was working just 3 days prior (without any changes to the workflow file) as you can see in this [successful run](https://github.com/qutip/qutip-virtual-lab/actions/runs/5892123732). I tried pinning the empack version to 3.1.0 but that didn't help.

I don't know too much about Pydantic, but willing to submit a patch if it's an easy fix.

**Comment by DerThorsten** [comment]
Probably some change in pydantic.
I have a look once I am back from vacation next week.
Thanks for reporting

**Comment by martinRenou** [comment]
Fixed in #79
